spring:
  application:
    name: galdcup

  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Seoul

  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}
      username: ${REDISUSER}
      password: ${REDISPASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

aes256:
  key: ${AES256_KEY}

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000
  refresh-expiration-days: 7

frontend:
  url: ${FRONTEND_URL}

cookie:
  secure: ${COOKIE_SECURE}
  sameSite: ${COOKIE_SAMESITE}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}