spring:
  application:
    name: galdcup

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-chuncheon-1.oraclecloud.com))(connect_data=(service_name=g2343d1e4dad721_galdcup_low.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: ADMIN
    password: ${ORACLE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Seoul

  data:
    redis:
      host: 10.0.0.223
      port: 6379
      password: ${REDISPASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

aes256:
  key: ${AES256_KEY}

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000
  refresh-expiration-days: 7

frontend:
  url: ${FRONTEND_URL}

cookie:
  secure: ${COOKIE_SECURE}
  sameSite: ${COOKIE_SAMESITE}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}